<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
		<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	
		
    </head>
	
	
	
	
	<script>
	
		$(document).ready(function(){ //전체문서를 읽고 준비되면 끝까지 읽어라
		
		
			$('#payment').click(function(){   //event를 거는함수이고 input값이 바뀔떄마다 특정 함수를 작동시켜라
			
			var _value = $('#valu').val() // value를 가져와서 넣어라
			
			$("#psd").val(_value)         
			
			
			
			})
		
		})

		
	
		
	</script>
	
	
	
    <body>
	
		
</body>
</html>